name: Trivy Docker Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t mi-imagen .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mi-imagen'
